apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: voyage-ml-network-policy
  namespace: voyage-ml
spec:
  podSelector:
    matchLabels:
      app: voyage-ml-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          name: default
    ports:
    - protocol: TCP
      port: 8000
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 5000
  - to:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
